parameters:
    database_driver:   pdo_mysql
    database_host:     remote-mysql3.servage.net
    database_port:     ~
    database_name:     lifereminder
    database_user:     lifereminder
    database_password: passwords123

    mailer_transport:  smtp
    mailer_host:       smtp1.servage.net
    mailer_user:       mkgxy@mkgalaxy.com
    mailer_password:   myflash74

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
