<?php

namespace Shaklee\PWSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PwsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PwsRepository extends EntityRepository
{
}
